apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: sequence-builder-vault
    kind: SecretStore
  target:
    name: postgres
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/sequence-builder/backend/postgres
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/sequence-builder/backend/postgres
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
      key: secret/sequence-builder/backend/postgres
      property: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgres # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:17-alpine
        envFrom:
        - secretRef:
            name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
