apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argocd
  namespace: argocd
  version: 8.2.2
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    configs:
      cm:
        #dex.config: |
        #  connectors:
        #    - type: oidc
        #      id: oidc
        #      name: OIDC
        #      config:
        #        issuer: https://chloeskim.cloudflareaccess.com/cdn-cgi/access/sso/oidc/adfcbe1c35582958b60a735468ff175a1309b012e737a895530fc6d7c615b0f8
        #        clientID: adfcbe1c35582958b60a735468ff175a1309b012e737a895530fc6d7c615b0f8
        #        clientSecret: $argocd-dex-oidc:clientSecret
        #        # Since no email verification was involved in creating CF Access App, disable this:
        #        insecureSkipEmailVerified: true
        kustomize.buildOptions: --enable-helm
        resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
          jsonPointers:
          - /spec/preserveUnknownFields
        resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
          jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
    global:
      domain: argocd.chloeskim.com

resources:
- cloudflared.yaml
- sa.yaml
- secrets.yaml
- secretstore.yaml
