apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argocd
  namespace: argocd
  version: 8.2.2
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    configs:
      cm:
        resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
          jsonPointers:
          - /spec/preserveUnknownFields 
        resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
          jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
