apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: argocd-vault
    kind: SecretStore
  target:
    name: cloudflared
  data:
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: secret/argocd/cloudflared
      property: TUNNEL_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-oidc
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: argocd-vault
    kind: SecretStore
  target:
    name: argocd-dex-oidc
  data:
  - secretKey: clientSecret
    remoteRef:
      key: secret/argocd/cloudflare-access/argocd-oidc
      property: clientSecret
