apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: sequence-builder-vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: rpi-chloe
          role: sequence-builder-default
          serviceAccountRef:
            name: default
