apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: gha-runner-scale-set
  includeCRDs: true
  releaseName: arc-sequence-builder-frontend
  namespace: sequence-builder
  version: 0.11.0
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  # Use values file because the current version of this chart has trouble with the githubConfigSecret value being set as a string here.
  valuesfile: arc-runners-frontend-values.yaml
- name: gha-runner-scale-set
  includeCRDs: true
  releaseName: arc-sequence-builder-backend
  namespace: sequence-builder
  version: 0.11.0
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  # Use values file because the current version of this chart has trouble with the githubConfigSecret value being set as a string here.
  valuesfile: arc-runners-backend-values.yaml

resources:
- secrets.yaml
