apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-secret
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: sequence-builder-vault
    kind: SecretStore
  target:
    name: arc-github-app-secret
  data:
  - secretKey: github_app_id
    remoteRef:
      key: secret/data/github/apps/chloeskimdev-github-actions-runner
      property: app-id
  - secretKey: github_app_installation_id
    remoteRef:
      key: secret/data/github/apps/chloeskimdev-github-actions-runner
      property: installation-id
  - secretKey: github_app_private_key
    remoteRef:
      key: secret/data/github/apps/chloeskimdev-github-actions-runner
      property: private-key
