apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - image: cloudflare/cloudflared:2025.7.0
        name: cloudflared
        envFrom:
        - secretRef:
            name: cloudflared
