apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: sequence-builder-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: chloesk/sequence-builder-frontend:0.0.2
        name: frontend
        env:
        - name: REACT_APP_API_URL
          value: "https://api.sequence-builder.chloeskim.com"
