apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: sequence-builder-vault
    kind: SecretStore
  target:
    name: cloudflared
  data:
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: secret/sequence-builder/cloudflared
      property: TUNNEL_TOKEN
